accelerate launch --mixed_precision="fp16"  "/content/drive/MyDrive/Colab Notebooks/riffusion/train_text_to_image.py" \
    --pretrained_model_name_or_path=riffusion/riffusion-model-v1 \
    --dataset_name="yihaoch/electro_spec_cap" \
    --resolution=512 \
    --use_ema \
    --train_batch_size=3 \
    --gradient_accumulation_steps=4 \
    --gradient_checkpointing \
    --max_train_steps=1000 \
    --learning_rate=1e-05 \
    --max_grad_norm=1 \
    --lr_scheduler="constant" --lr_warmup_steps=0 \
    --output_dir="finetune_electro_2" \
    --push_to_hub