accelerate launch --mixed_precision="fp16"  train_text_to_image.py ^
    --pretrained_model_name_or_path=riffusion/riffusion-model-v1 ^
    --dataset_name=DaveLoay/NSynth_Bass_Captions ^
    --resolution=512 ^
    --use_ema ^
    --train_batch_size=3 ^
    --gradient_accumulation_steps=4 ^
    --gradient_checkpointing ^
    --max_train_steps=4000 ^
    --learning_rate=1e-05 ^
    --max_grad_norm=1 ^
    --lr_scheduler="constant" --lr_warmup_steps=0 ^
    --output_dir="Riffusion_FT_Bass_512_4000" ^